######
###### All scripts were run from a conda environment made from this file.
######
###### OS  -----------  Windows 10, version 21H1, OS build 19043.1466
###### miniconda  ----  conda version 4.10.3
######
###### $ conda env create --file environment.yml
######
###### See environment.txt for specifics (e.g., version numbers).
######

name: lsub

dependencies:

  - ipython                   # development
  - conda-forge::tqdm         # progress bars
  - conda-forge::osfclient    # uploading materials

  - numpy                     # data analysis
  - pandas                    # data analysis
  - scipy                     # data analysis
  - conda-forge::pingouin     # data analysis - statistics
  - openpyxl                  # data analysis - read excel into pandas

  - matplotlib                # data visualization
  - seaborn                   # data visualization
  - conda-forge::colorcet     # data visualization - colormaps
  - python-graphviz           # visualization - box/arrow diagrams
  
  - pip
  - pip:
    - psaw                    # web scraping - Reddit access